name: projeto-devops

on:
  push: 
    branches:
      - main 
  # pull_request:
  #   branches:
  #     - main 
      
  # release:
  #   types: [created]
env:
  NODE_VERSION: '20'
  
# https://github.com/marketplace?type=actions


# job 1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download Repo
        uses: actions/checkout@v4

    # checkout@4 é um clona o repo dentro do ubuntu


    # Setup node faz a instalação do node
      - name: Prepara S.O para Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION}}


  # Pra colocar varios comandandos u em baixo do outro, coloca run e coloca um | se não ele não deixa colocar embaixo um do outro
  # dica, sempre importante colcoar um ls ou pwd para mostrar onde esta o diretorio caso de um erro
      - name: Ajuste path e Adiciona Files
        run: | 
          pwd && ls -alh 
          cd mini-curso-devops
          cat << EOF >> vite.config.js
          import { defineConfig } from 'vite'
          // https://vitejs.dev/config/
          export default defineConfig({
          // Adicione esta linha:
          base: '/mini-curso-devops/', 
          } )
          EOF
          ls -alh


      - name: Instala dependencias e Build
        run: |
          pwd && ls -alh  
          cd mini-curso-devops         
          npm install
          npm run build

      - name: Fazer o Upload do codigo
        uses: actions/upload-artifact@v4
        with: 
          name: dist-files
          path: mini-curso-devops/dist


#job 2

  deploy:
    runs-on: ubuntu-latest
    needs: build-minicurso
    steps:
      - name: Download do Arquivos 
        uses: actions/download-artifact@v4
        with: 
          name: dist-files
          path: dist
      - name: Enviar arquivos para Server 
        run: | 
          ls -alh 
          mkdir -p ~/.ssh
          echo "${{ secrets.KOEHLERLABS_KEY_PROD }}" > ~/.ssh/koehlerlabs-key-prod.pem
          chmod 600 ~/.ssh/koehlerlabs-key-prod.pem
          scp -i ~/.ssh/koehlerlabs-key-prod.pem  -o StrictHostKeyChecking=no -r dist/* ubuntu@ec2-54-221-104-150.compute-1.amazonaws.com/var/www/html/mini-curso-devops
          

